### ISSUE TITLE
Article preview doesn't work

### ISSUE THREAD

**Issue by AnnKats93** [unitedforukraine/refugee.info-greece#7]
Open: https://refugee-info-greece.vercel.app/api/preview?slug=/en-us/articles/6772293028765$secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

Gives "{"message":"Invalid token"}" message.
It doesn't seem to be an issue of Zendesk OAuth token ,since I also tried Beporsed's and U4U tokens and they give the same error.

@jennytick @ishparii  do we have to do any additional steps to make Article preview work?

**Comment by jennytick** [comment]
@Guiso92 preview mode in Refugee.info works correctly.

The Next.js preview link from the description contains a mistake. The correct link is 
https://refugee-info-greece.vercel.app/api/preview?slug=/en-us/articles/6772293028765&secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 where the params in the link must be concatenated with `&` instead of `$`.
